name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build and Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            npm run build:linux
          elif [ "$RUNNER_OS" == "Windows" ]; then
            npm run build:win
          else
            npm run build:mac
          fi
        shell: bash
